name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Asegúrate de que tu rama principal se llame 'main' o 'master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Deploy a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . # Esto indica que el sitio está en la raíz del repo
